name: Java 21, 25 CI

on: [ push,pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDKs 21, 25
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: |
            21
            25

      - name: Build with Gradle
        run: ./gradlew assemble

      - name: Test with Java 21
        id: test_java21
        run: ./gradlew test -PtestOnJava=21 --stacktrace

      - uses: actions/upload-artifact@v4  # upload test results if the test was not skipped
        if: ${{ !cancelled() && steps.test_java21.outcome != 'skipped'}}
        with:
          name: test-results-j21
          path: '*/build/test-results/**/*.xml'
          overwrite: 'true'

      - name: Test with Java 25
        id: test_java25
        run: ./gradlew test -PtestOnJava=25 --stacktrace

      - uses: actions/upload-artifact@v4  # upload test results if the test was not skipped
        if: ${{ !cancelled() && steps.test_java25.outcome != 'skipped'}}
        with:
          name: test-results-j25
          path: '*/build/test-results/**/*.xml'
          overwrite: 'true'

