name: Create Release

on:
  workflow_dispatch:
    inputs:
      bumpType:
        description: 'Bump type (patch, minor, major)'
        required: true
        type: string
        default: 'minor'

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    timeout-minutes: 60
    if: github.repository == 'RoaringBitmap/RoaringBitmap'
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: true
          validate-wrappers: false

      - name: Configure git user
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Create release
        run: ./gradlew release -Prelease.releaseVersionBump=${{ github.event.inputs.bumpType }}

      - name: Get tag name
        run: echo "TAG_NAME=$(git tag | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -1)" >> $GITHUB_ENV

      - name: Publish Maven artifacts
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSPHRASE }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.MAVEN_USER }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.MAVEN_PASSWORD }}
        run: ./gradlew publishAggregationToCentralPortal --no-scan
      # Publishing to GitHub Packages is currently disabled because it fails
      # - name: Publish package
      #   run: ./gradlew publishSonatypePublicationToGitHubPackagesRepository -i
      #   env:
      #     GITHUB_USER: ${{ github.actor }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}